# Generated by Django 4.0.5 on 2022-07-18 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labeltask', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LAdequacy', models.IntegerField(help_text='0, 1', null=True)),
                ('LDeducibility', models.IntegerField(help_text='0, 1', null=True)),
                ('LAbstractive', models.IntegerField(help_text='0, 1', null=True)),
                ('LNote', models.CharField(blank=True, help_text='備註', max_length=30, null=True)),
                ('LLabel_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeltask.setlabeltask')),
                ('LUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
