# Generated by Django 4.0.5 on 2022-07-18 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qQuestion_ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('qQuestion_Title', models.CharField(max_length=100)),
                ('qOriginal_Question', models.TextField(max_length=1000)),
                ('sQuery', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('sQuestion_Type', models.PositiveSmallIntegerField(choices=[(0, '未選擇 NOT selected'), (1, '病症 symptoms'), (2, '藥物 drugs'), (3, '科室 department'), (4, '治療 treatment'), (5, '檢查 examination'), (6, '資訊 informantion')], default=None, null=True)),
                ('sQuestion_Filter', models.PositiveSmallIntegerField(choices=[(0, "Haven't filter"), (1, 'Single'), (2, 'Single & Often'), (3, 'Multi'), (4, 'Discuss'), (5, 'Trash')], default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Summarization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_stamp', models.TimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('sUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
