# Generated by Django 4.0.5 on 2022-08-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='sQuestion_Type',
            field=models.PositiveSmallIntegerField(choices=[(0, '未選擇 NOT selected'), (1, '病症 symptoms'), (2, '藥物 drugs'), (3, '科室 department'), (4, '治療 treatment'), (5, '檢查 examination'), (6, '資訊 informantion'), (7, '再討論...')], default=None, null=True),
        ),
    ]
