# Generated by Django 4.0.5 on 2022-07-18 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SetTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tStartTime', models.DateField(default=django.utils.timezone.now)),
                ('tdone', models.BooleanField(default=False)),
                ('tQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('tUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
